stages:
  - sync

sync_to_github:
  stage: sync
  script:
    - git remote add github https://$CI_PROJECT_NAMESPACE:$GITHUB_TOKEN@github.com/empty-labs/jam-buddy.git
    - git push github main
  only:
    - main
