stages:
  - sync

sync_to_github:
  stage: sync
  image: alpine:latest
  script:
    - apk add git openssh
    - git remote remove github || true
    - git remote add github https://$CI_PROJECT_NAMESPACE:$GITHUB_TOKEN@github.com/empty-labs/jam-buddy.git
    - git config --global user.email "mdt2014@gmail.com"
    - git config --global user.name "Matthew Taylor"
    - git fetch --all
    - git branch -r
    - git remote set-url --push origin git@gitlab.com:empty-labs/jam-buddy.git
    - git push github --mirror  # <- this is the magic: pushes *everything
  only:
    - main
